#
# /etc/timeshift-autosnap.conf
#

# skipAutosnap defines whether timeshift-autosnap execution should be skipped.
# Default: false
skipAutosnap=false

# skipRsyncAutosnap defines whether timeshift-autosnap should be skipped on filesystems other than BTRFS.
# This helps avoid snapshot attempts on unsupported or rsync-based systems.
# Default: true
skipRsyncAutosnap=true

# deleteSnapshots defines whether old snapshots created by timeshift-autosnap should be deleted.
# Default: true
deleteSnapshots=true

# maxSnapshots defines how many recent snapshots should be kept.
# Only positive whole numbers are valid.
# Default: 3
maxSnapshots=3

# updateGrub defines whether GRUB entries should be regenerated after snapshot creation.
# If the grub-btrfs package is not installed, this will be skipped.
# Default: true
updateGrub=true

# snapshotDescription defines a unique label used to identify snapshots created by timeshift-autosnap.
# Default: {timeshift-autosnap} {created before upgrade}
snapshotDescription=[timesnap] Pre-upgrade
